name: Testing
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Tests
    name: Tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build HellWorldApp'
        run: javac src/HelloWorldApp.java -d .
      - name: 'Build HellWorldAppTest'
        run: javac test/HelloWorldAppTest.java -d .
      - name: 'Run HelloWorldAppTest'
        run: java HelloWorldAppTest
